language: erlang

env:
  - LUA="luajit"

branches:
  only:
    - master

install:
  - git clone http://luajit.org/git/luajit-2.0.git && cd luajit-2.0 && sudo make install && sudo ln -sf luajit-2.0.3 /usr/local/bin/luajit && cd ..
  - sudo apt-get install luarocks
  - sudo luarocks install luafilesystem
  - sudo luarocks install busted
  - sudo make install
  - sudo rm /usr/bin/lua
  - sudo ln -s /usr/local/bin/luajit /usr/bin/lua

script: "make test"

notifications:
  recipients:
    - jhnabrhmsn@gmail.com
  email:
    on_success: change
    on_failure: always
